// Regenerates src/lib/fontsCss.ts: downloads the brand fonts from Google Fonts
// (latin subset, woff2) and embeds them as base64 @font-face rules so renders
// never touch the network. Run: node scripts/gen-fonts.mjs
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const FAMILIES = [
  { name: "Space Grotesk", weights: [400, 500, 700] },
  { name: "Inter", weights: [400, 500, 600] },
  { name: "JetBrains Mono", weights: [400, 500, 700] },
];

// Chrome UA → Google serves woff2
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const fetchText = async (url) => {
  const r = await fetch(url, { headers: { "User-Agent": UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r.text();
};

const fetchB64 = async (url) => {
  const r = await fetch(url, { headers: { "User-Agent": UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return Buffer.from(await r.arrayBuffer()).toString("base64");
};

let css = "";
for (const fam of FAMILIES) {
  for (const weight of fam.weights) {
    const apiUrl = `https://fonts.googleapis.com/css2?family=${fam.name.replace(/ /g, "+")}:wght@${weight}&display=block`;
    const sheet = await fetchText(apiUrl);
    // take the latin block (last /* latin */ section) → its woff2 URL
    const blocks = sheet.split("/* ");
    const latin = blocks.find((b) => b.startsWith("latin */")) ?? blocks[blocks.length - 1];
    const url = latin.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) throw new Error(`no woff2 url for ${fam.name} ${weight}`);
    const b64 = await fetchB64(url);
    css += `@font-face{font-family:'${fam.name}';font-style:normal;font-weight:${weight};font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;}`;
    console.log(`${fam.name} ${weight}: ${Math.round(b64.length / 1024)}kb`);
  }
}

const out = `// AUTO-GENERATED by scripts/gen-fonts.mjs — base64-embedded fonts (no network fetch
// → deterministic, never stalls a render). Regenerate: node scripts/gen-fonts.mjs
export const FONTS_CSS = ${JSON.stringify(css)};
`;
const dest = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "lib", "fontsCss.ts");
writeFileSync(dest, out);
console.log(`wrote ${dest}`);
